# Generated by Django 5.1.2 on 2024-10-30 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='observacoes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
